name: clones_desktop
description: "A desktop application for contributing to the world's largest dataset for multimodal computer-use agents."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:

  audioplayers: ^6.4.0  
  auto_size_text: ^3.0.0
  collection: any
  crypto: any
  decimal: ^3.2.2
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  file_saver: ^0.2.13
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.4.4
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  graphview: ^1.2.0
  http: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.8.1
  lucide_icons_flutter: ^3.0.5
  percent_indicator: ^4.2.5
  riverpod: any
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.0
dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.6.4
  daunused: ^1.6.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

dependency_overrides:
  font_awesome_flutter: 10.4.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/menus/
    - .env

