name: viralmind_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  lucide_icons_flutter: ^3.0.5
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  http: ^1.2.1
  fluttertoast: ^8.2.4
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.4
  video_player: ^2.10.0
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.2
  riverpod_annotation: ^2.6.1
  go_router: ^13.2.0
  intl: ^0.20.2
  gradient_borders: ^1.0.1
  audioplayers: ^6.4.0
  dio: ^5.8.0+1
  graphview: ^1.2.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.0
  build_runner: ^2.4.6
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
dependency_overrides:
  analyzer_plugin: ^0.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env

